# -*- coding: utf-8 -*-
"""Live-Speech-To_Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTjvaLTpXu2OIauWLA4L_Tlr1kcG6_-n
"""

!pip uninstall torch torchvision torchaudio whisper openai-whisper -y
!pip cache purge

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install openai-whisper

! pip install git+https://github.com/openai/whisper.git -q

import whisper

model = whisper.load_model("base")

model.device

! pip install gradio -q

!pip install gradio --upgrade

import gradio as gr
import time

from IPython.display import Audio

def transcribe(audio):

  # load audio and pad/trim it to fit 30 seconds
  audio = whisper.load_audio(audio)
  audio = whisper.pad_or_trim(audio)

  mel = whisper.log_mel_spectrogram(audio).to(model.device)

  # detect the spoken language
  _, probs = model.detect_language(mel)
  print(f"Detected language: {max(probs, key=probs.get)}")

  options = whisper.DecodingOptions()
  result = whisper.decode(model, mel, options)

  return result.text

gr.Interface(
    title = 'OpenAI Whisper ASR Gradio Web UI',
    fn=transcribe,
    inputs=gr.Audio(sources=["microphone"], type="filepath"),
    outputs="textbox",
    live=True).launch(share=True)

